
DELETE http://localhost:3000/api/blog/660ab32536ffc06b4b152a2b

###

POST http://localhost:3000/api/blog
Content-Type: application/json

{
    "title": "checking on new post functionality",
    "author": "Soh Wen Ming", 
    "url": "http://localhost:3000", 
    "likes": 3
}

###
PUT http://localhost:3000/api/blog/660ab6e68b906ba9bd567a8e
Content-Type: application/json

{
    "title": "test title edited 2",
    "author": "Soh Wen Ming's bastard motherfucker twin", 
    "url": "http://localhost:3000", 
    "likes": 3
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "something": "something"
}