POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "baseUser",
    "name": "Base User",
    "password": "Holoq123holoq123"
}

###
POST http://localhost:3000/api/blog 
Content-Type: application/json

{
    "title": "this is the first post",
    "url": "https://idied.here.com",
    "likes": 0,
    "author": "Soh Wen Ming",
    "userId": "66275375101e4d1a72f817b6"
}


